// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdmmlycxabdgyzbabkco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbW1seWN4YWJkZ3l6YmFia2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjkzMTIsImV4cCI6MjA2NTQwNTMxMn0.uNeXpmqOpggnwrR4InkgDUH7X2VEEYWXMNcvzu4Qpno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);